services:
  - type: web
    name: StarsExchangrBot # This will be the name of your web service on Render
    env: python
    plan: free # Free tier plan
    buildCommand: "pip install -r requirements.txt"
    # Correct start command: points to flask_app in Stars.py
    startCommand: "gunicorn Stars:flask_app --workers 4 --bind 0.0.0.0:$PORT"
    healthCheckPath: / # Add a simple health check to the root path
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12 # Ensure this matches your Python version
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Render will prompt you for this value in the dashboard
      - key: WEBHOOK_URL
        sync: false # Render will prompt you for this value in the dashboard
      - key: NOWPAYMENTS_API_KEY
        sync: false # Render will prompt you for this value in the dashboard
      - key: IPN_SECRET_KEY
        sync: false # Render will prompt you for this value in the dashboard